### ISSUE TITLE
Choppy video

### ISSUE THREAD

**Issue by mkeryeski** [pelya/commandergenius#39]
Trying to run a PC-based arcade game on my MemoPad 7 tablet (x86). 1 GB RAM, CPU Intel Atom Z3745.  This runs perfectly on identical hardware on a PC running puppylinux.  But it's choppy to the point of being unplayable on my tablet.  I am preloading the x86 libandroid-shmem.so file and have the video in a different thread (option in the gui of xserver-xsdl). Anyone else have any suggestions?

**Comment by pelya** [comment]
Video is choppy because Debian has no direct hardware access, and there's
nothing I can do to fix that.
If the game uses OpenGL, Debian will be running software rendering, and
this is of course slow.
Even if it does not use OpenGL, there still is extensive memory copying
between all layers of video output. If you select custom video mode during
app startup, which matches exactly the video mode used in the game, and run
your game in a full screen, it should be somewhat faster.

**Comment by mkeryeski** [comment]
Running `glxinfo | grep rend` shows me Direct rendering: yes .. know of any other distros that I could bootstrap to test that would support direct rendering?

**Comment by pelya** [comment]
Debian uses libgl1-mesa-swx11 library to output OpenGL, which is a software
renderer, it does not matter what glxinfo says.
If you want OpenGL to stop working at all, you may try to install
libgl1-mesa-dri library, which is the direct renderer.
Anyway, mobile phones only support GLES libraries, they do not support full
OpenGL stack, and there's no easy way to fix that.
There was one library, which simulated full OpenGL stack on GLES, but it's
still in beta, and integrating it with X server will be a huge effort.

**Comment by pelya** [comment]
Won't fix, closing this bug.
