### ISSUE TITLE
Update SuperTux to version 0.3.5a

### ISSUE THREAD

**Issue by tobbi** [pelya/commandergenius#45]
Hey,
I'm one of the developers of the SuperTux team. Would it be possible to update the Android port to version 0.3.5a?

You can find our github organization here: http://github.com/supertux/

Thanks in advance.

**Comment by pelya** [comment]
Yes, it would be possible, I will update it when I'll have some free time,
probably in a week or two.

BTW there is an issue with FPS on some later levels, could be too many
OpenGL render commands, or semi-transparent water textures, I did not
investigate yet. It's running slowly even on Note 3, which  runs
graphically-intensive games like XCOM with no issues.

**Comment by tobbi** [comment]
If this is an issue with 0.3.4, there's a slight change it's been fixed since then. We've updated 0.3.5 to use SDL2 for graphics rendering.

**Comment by gerstrong** [comment]
Oh yeah, more SDL2. I should take another on that...

**Comment by pelya** [comment]
Don't bother, I'll just port it back to SDL1.2, this will be easier.

**Comment by gerstrong** [comment]
Ok, Freeheroes 2 seems to have a similar issue. Just looking at the code. It seems the author got a bit confused between sdl 1.2 and 2.0 because some routines called are exclusive to SDL 2.0 and used for 1.2 when Android macro is used. It seems a bit strange to me...  I'm going to backport for SDL 1.2 that one, but we should think about supporting both in future...

**Comment by tobbi** [comment]
Why port SuperTux back to SDL 1.2? Isn't 2.0 hardware-accelerated and all that?

**Comment by pelya** [comment]
There are three SDL ports to Android.
SDL1.2, which is this repository, is what you're seeing in SuperTux Android
port, it has overlay keys and game data downloader.

There is official SDL2 from libsdl.org, which does not have overlay keys
and data downloader, so your game need to be able to load all it's data
from a single archive (using libzzip for example), because Google Play only
allows to upload two 2Gb files with the app, and puts them to predefined
location (and if you want to distribute app from your site, you need data
downloader anyway).

The third port is our own SDL2 port, which is currently unusable, but with
ambitious plans to add overlay keys.

Also there are plans to create separate library for SDL2, which will draw
and handle overlay keys.

If you're using OpenGL, there is not much difference between SDL1.2 and
SDL2.

Why port SuperTux back to SDL 1.2? Isn't 2.0 hardware-accelerated and all
that?

**Comment by pelya** [comment]
Updated Android release to 0.3.5a, I'll check if it actually works tomorrow.

**Comment by pelya** [comment]
Sources of Android version: https://sourceforge.net/projects/libsdl-android/files/apk/SuperTux/

**Comment by tobbi** [comment]
Working great on my Samsung Galaxy Tab 10.1 so far. Thank you! :-)
