### ISSUE TITLE
Update SuperTux to version 0.4.0

### ISSUE THREAD

**Issue by tobbi** [pelya/commandergenius#48]
We just released a new stable version of SuperTux (Milestone 2). You can grab the source code from here:
https://github.com/SuperTux/supertux/releases/tag/v0.4.0

Don't hesitate to ask if you have any questions.

xref https://github.com/SuperTux/supertux/issues/243

**Comment by pelya** [comment]
Okay, will do next week.

**Comment by gerstrong** [comment]
Hi Pelya,

will you remove the SDL 2 stuff with your patches in this version, like 
you did with 0.3.5?

Btw. have you heard about dropping GCC and using Clang in future NDKs of 
Android? It was in the news yesterday I think...

Take care!
- Gerd

Am 20.12.2015 um 16:06 schrieb Sergii Pylypenko:

> Okay, will do next week.

**Comment by pelya** [comment]
Yes, I'll patch SuperTux up to build with our version of SDL 1.2.
Both ours and official SDL2 still miss features, like overlay buttons and
gamepad support (maybe official one supports gamepads, I did not check in a
long time).

I did not hear about NDK and Clang, I've just checked developer.android.com
and latest  NDK is still r10e.

**Comment by gerstrong** [comment]
Am 23.12.2015 um 12:27 schrieb Sergii Pylypenko:

> Yes, I'll patch SuperTux up to build with our version of SDL 1.2.
> Both ours and official SDL2 still miss features, like overlay buttons and
> gamepad support (maybe official one supports gamepads, I did not check 
> in a
> long time).

Yeah, that's right. Our SDL2 works but no overlay for buttons. I really 
would like to enhance CG for that, and already there is C++ Overlay, but 
it's still unfinished. Now there is Keen Dreams support in the latest 
version, fan pressure, so I might work on that and maybe we can use it 
in other games. SDL2 supports native touch support, so the developers of 
the apps should support gestures, but that will be hard. I see a 
conflict there. So in conclusion we are best served with SDL 1.2. Most 
SDL2 Dev users I consider seem not use those gestures, so there opens 
the question: what is really the workload of a porter. The main devs 
should concentrate more on gestures which depend on the game itself 
rather than a virtual gamepad all the time there, but that is not going 
to happen with most of the games, I guess.

I want to make Commander Genius boot on android with SDL2. Actually this 
works up until the game selection. So we are almost there. But controls 
is still a big question. I want to support gestures in Commander Genius. 
There are some ideas, but I need more time for that...

Having a job makes this difficult sometimes...

> I did not hear about NDK and Clang, I've just checked 
> developer.android.com
> and latest NDK is still r10e.

Yeah, that worries me a bit. I think the next will be much bigger. It 
was in the german IT-News of Golem.de. Searching I found this:

https://android.googlesource.com/platform/ndk.git/+/master/CHANGELOG.md

So, I think they are going to do it, kick GCC out. I doubt it will a big 
issue though. I really like the idea of llvm and clang. I used a bit and 
really like the concept. I'm not sure if we have to build all the stuff, 
but the compatibility to the standard is pretty good.

I tried to compile Commander Genius with clang and never ran into 
problems, so that's a plus for me...

**Comment by pelya** [comment]
I seriously doubt they can kick out GCC completely, because it's always an
unplanned time investment to switch over all your build files, so devs will
probably simply keep using old NDK.
Hopefully it would be as simple as replacing all
'arm-linux-androideabi-gcc' strings with 'clang' in build files.

You can see the point of view from both sides - SDL/framework developers
just provide raw touchscreen API and call it a day. Game developers want
buttons and gestures in a simpler way, ideally as simple as receiving
SDLK_SWIPE_LEFT 'button press' gesture, they don't need raw input and
implementing gesture detection on their own, and that's what our SDL1.2
port tries to provide, to an extent. The porter's job lies somewhere
in-between, it is to bind all game actions to some input more suited for
the device, e.g. swipe instead of keypress, double-tap instead of mouse
right button. And if you want to do two virtual joysticks or swipe actions
on each part of the screen, something ridiculous like
SDLK_SWIPE_LEFT_ON_THE_LEFT_PART_OF_THE_SCREEN will make porters very
happy, because it's simple API, replacing usual button presses in the game
code with minimal effort.

My idea about the situation was to take input processing code out of our
port, and convert it into a library for SDL2, which would somehow plug into
raw API and provide simpler, button-press-like API, which would ideally
provide single function like ProcessEvents for all SDL events, and return
you for example a gamepad-like button presses and virtual joysticks,
activated by touchscreen gestures or gamepad or mouse+keyboard, whatever
input options you have for your device.

But again, I am currently too lazy to take on this task, plus there will be
no immediate feedback, as other devs need some time to get familiar with
this new lib and integrate it and get back to you with suggestions.

I also cannot assess real SDL2 popularity among game devs, as they got a
lot to choose from - Unity non-commercial offering for example, we cannot
really compete with that, so our niche is 'traditional' open-source games
with active developers, which aren't that numerous, but it's whole other
topic.

**Comment by pelya** [comment]
Updated: https://sourceforge.net/projects/libsdl-android/files/apk/SuperTux/
